apiVersion: v1
kind: Service
metadata:
  name: oryx-core-service
  namespace: oryx-fund-production
  labels:
    app: oryx-core-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: oryx-core-api
